In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing

penguins = pd.read_csv("penguins.csv")
penguins = penguins.sample(frac = 1)
penguins = penguins.dropna()

ModuleNotFoundError: No module named 'pandas'

In [79]:
penguins.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g     sex
78      Adelie  Torgersen              36.2             16.1              187.0       3550.0  FEMALE
76      Adelie  Torgersen              40.9             16.8              191.0       3700.0  FEMALE
183  Chinstrap      Dream              54.2             20.8              201.0       4300.0    MALE
226     Gentoo     Biscoe              45.4             14.6              211.0       4800.0  FEMALE
0       Adelie  Torgersen              39.1             18.7              181.0       3750.0    MALE

In [80]:
penguins_x = pd.concat([penguins[['body_mass_g', 'culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

body_mass_g  culmen_length_mm  culmen_depth_mm  flipper_length_mm      .  FEMALE   MALE
78        3550.0              36.2             16.1              187.0  False    True  False
76        3700.0              40.9             16.8              191.0  False    True  False
183       4300.0              54.2             20.8              201.0  False   False   True
226       4800.0              45.4             14.6              211.0  False    True  False
0         3750.0              39.1             18.7              181.0  False   False   True
..           ...               ...              ...                ...    ...     ...    ...
285       5700.0              49.8             16.8              230.0  False   False   True
150       3700.0              36.0             17.1              187.0  False    True  False
84        3350.0              37.3             17.8              191.0  False    True  False
247       5650.0              47.8             15.0              215.0  False   False   True
313       5650.0              49.5             16.1              224.0  False   False   True

[334 rows x 7 columns]

In [81]:
penguins_x = penguins_x.drop('.', axis=1)


In [82]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

body_mass_g  culmen_length_mm  culmen_depth_mm  flipper_length_mm  FEMALE  MALE
0       0.236111          0.149091         0.357143           0.254237     1.0   0.0
1       0.277778          0.320000         0.440476           0.322034     1.0   0.0
2       0.444444          0.803636         0.916667           0.491525     0.0   1.0
3       0.583333          0.483636         0.178571           0.661017     1.0   0.0
4       0.291667          0.254545         0.666667           0.152542     0.0   1.0
..           ...               ...              ...                ...     ...   ...
329     0.833333          0.643636         0.440476           0.983051     0.0   1.0
330     0.277778          0.141818         0.476190           0.254237     1.0   0.0
331     0.180556          0.189091         0.559524           0.322034     1.0   0.0
332     0.819444          0.570909         0.226190           0.728814     0.0   1.0
333     0.819444          0.632727         0.357143           0.881356     0.0   1.0

[334 rows x 6 columns]

In [83]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

78        Adelie
76        Adelie
183    Chinstrap
226       Gentoo
0         Adelie
         ...    
285       Gentoo
150       Adelie
84        Adelie
247       Gentoo
313       Gentoo
Name: species, Length: 334, dtype: object
78        Adelie
76        Adelie
183    Chinstrap
226       Gentoo
0         Adelie
         ...    
285       Gentoo
150       Adelie
84        Adelie
247       Gentoo
313       Gentoo
Name: species, Length: 334, dtype: object


array([0, 0, 1, 2, 0, 1, 2, 0, 0, 2, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 2, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2,
       2, 0, 2, 1, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 1, 0, 2, 0, 2, 2, 0, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0, 2, 0, 1, 0, 2,
       0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 0, 1, 1, 0, 2, 2, 2, 2, 1, 0, 0, 2, 2, 1, 0, 1, 1, 0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 0, 0, 0, 1, 2, 0, 1, 0, 2, 2, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 1, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 2, 0, 0,
       0, 2, 2, 0, 0, 0, 0, 2, 1, 2, 1, 0, 1, 1, 2, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 2, 1, 2, 2, 2, 0, 2, 1, 0, 0, 2, 2, 2, 2, 1, 0, 2, 0, 2, 0, 1, 0, 1, 2, 0, 0, 2, 2, 0, 0, 2, 1, 2, 1, 0, 1, 1, 1, 0, 2, 1, 2, 1, 0, 0,
       2, 2, 1, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 1, 2, 1, 0, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 

### Building the Neural Network

In [84]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [85]:
model.summary()

Model: "penguin_model"
Model: "penguin_model"


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_6 (InputLayer)           │ (None, 6)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_24 (Dense)                     │ (None, 7)                   │              49 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_25 (Dense)                     │ (None, 5)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_26 (Dense)                     │ (None, 3)                   │              18 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_27 (Dense)   

 Total params: 119 (476.00 B)
 Total params: 119 (476.00 B)


 Trainable params: 119 (476.00 B)
 Trainable params: 119 (476.00 B)


 Non-trainable params: 0 (0.00 B)
 Non-trainable params: 0 (0.00 B)


In [86]:
keras.utils.plot_model(model, show_shapes=True)


You must install pydot (`pip install pydot`) for `plot_model` to work.
You must install pydot (`pip install pydot`) for `plot_model` to work.


In [88]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1, verbose=0)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=0)

/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/nn.py:708: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/nn.py:708: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


In [1]:
model_scaled = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_scaled.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_scaled = model_scaled.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1, verbose=0)

scores = model_scaled.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

NameError: name 'keras' is not defined

In [90]:
model_scaled.predict(scaled_penguins_x)

 1/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


array([[0.78058887, 0.44495174, 0.21605189],
       [0.78058887, 0.44495174, 0.21605189],
       [0.18599166, 0.98079133, 0.00833914],
       ...,
       [0.78058887, 0.44495174, 0.21605189],
       [0.01388541, 0.00350944, 0.9978513 ],
       [0.00736454, 0.00457565, 0.99767864]], dtype=float32)

In [91]:
penguins['species']

78        Adelie
76        Adelie
183    Chinstrap
226       Gentoo
0         Adelie
         ...    
285       Gentoo
150       Adelie
84        Adelie
247       Gentoo
313       Gentoo
Name: species, Length: 334, dtype: object

In [93]:
penguins_y

array([0, 0, 1, 2, 0, 1, 2, 0, 0, 2, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 2, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2,
       2, 0, 2, 1, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 1, 0, 2, 0, 2, 2, 0, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0, 2, 0, 1, 0, 2,
       0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 0, 1, 1, 0, 2, 2, 2, 2, 1, 0, 0, 2, 2, 1, 0, 1, 1, 0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 0, 0, 0, 1, 2, 0, 1, 0, 2, 2, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 1, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 2, 0, 0,
       0, 2, 2, 0, 0, 0, 0, 2, 1, 2, 1, 0, 1, 1, 2, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 2, 1, 2, 2, 2, 0, 2, 1, 0, 0, 2, 2, 2, 2, 1, 0, 2, 0, 2, 0, 1, 0, 1, 2, 0, 0, 2, 2, 0, 0, 2, 1, 2, 1, 0, 1, 1, 1, 0, 2, 1, 2, 1, 0, 0,
       2, 2, 1, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 1, 2, 1, 0, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 